[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "rjpop"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "astropy",
    "h5py",
    "matplotlib",
    "seaborn",
    "corner",
    "scikit-learn",
    "eryn",
    "popsummary",
    "cupy-cuda13x",
    "KDEpy",
]

[tool.hatch.build.targets.wheel]
packages = ["rjpop"]
