universe = vanilla
executable = submit.sh

arguments = /data/aqc/rjmcmc_pop/results/MDC_PLP/args.txt

# Request resources
request_cpus = 1
request_gpus = 1

request_memory = 64GB

# Specify output, error, and log files
logs = /data/aqc/rjmcmc_pop/results/logs
output = $(logs)/$(Cluster).out
error = $(logs)/$(Cluster).err
log = $(logs)/$(Cluster).log

stream_output = true
stream_error = true

# Notify on completion
# notification = Complete
# notify_user = aqcheng@aei.mpg.de

# Queue the job
queue